# Site setings
name: 'Tek-Write'
description: 'A blog about the practices of leading-edge technical writing'
meta_description: 'A blog for anyone interested in the techniques of modern technical writing'
greetings: 'Modern Technical Writing'
logo:
favicon: 'assets/images/favicon.ico'
baseurl:
production_url:
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: covers/6.jpeg
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'username'
facebook: 'username'
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'username'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-asciidoc
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title:output_ext

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Build settings
asciidoctor:
  attributes:
    - hardbreaks!

# recognize these extensions
asciidoc_ext: asciidoc,adoc,ad

encoding: utf-8

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
